name: locksmith-tests

on:
  push:
    paths: 
      - "packages/locksmith/**"
  pull_request:
    paths: 
      - "packages/locksmith/**"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      DB_USERNAME: locksmith_test
      DB_PASSWORD: password
      DB_NAME: locksmith_test
      DB_HOSTNAME: db
    steps:
      - uses: actions/checkout@v2
      - name: Running tests
        run: scripts/tests.sh packages/locksmith