name: Unlock-JS

on:
  push:
    - "packages/unlock-js/*"
  pull_request:
    - "packages/unlock-js/*"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      BLOCKTIME: 0
    steps:
      - uses: actions/checkout@v2
      - name: Running tests
        run: scripts/tests.sh packages/unlock-js